[workspace]
members = ["coordinator", "mobile/native/", "crates/*"]
resolver = "2"

[patch.crates-io]
dlc-manager = { git = "https://github.com/get10101/rust-dlc", rev = "3c57f779a1c6f10db19630af7e8d34a69d0e4c39" }
dlc-messages = { git = "https://github.com/get10101/rust-dlc", rev = "3c57f779a1c6f10db19630af7e8d34a69d0e4c39" }
dlc-sled-storage-provider = { git = "https://github.com/get10101/rust-dlc", rev = "3c57f779a1c6f10db19630af7e8d34a69d0e4c39" }
lightning = { git = "https://github.com/get10101/rust-lightning/", rev = "77fc8a11b0f10fb7e31f246b59a37455d4f0d41d" }
lightning-background-processor = { git = "https://github.com/get10101/rust-lightning/", rev = "77fc8a11b0f10fb7e31f246b59a37455d4f0d41d" }
lightning-block-sync = { git = "https://github.com/get10101/rust-lightning/", rev = "77fc8a11b0f10fb7e31f246b59a37455d4f0d41d" }
lightning-net-tokio = { git = "https://github.com/get10101/rust-lightning/", rev = "77fc8a11b0f10fb7e31f246b59a37455d4f0d41d" }
lightning-persister = { git = "https://github.com/get10101/rust-lightning/", rev = "77fc8a11b0f10fb7e31f246b59a37455d4f0d41d" }
lightning-rapid-gossip-sync = { git = "https://github.com/get10101/rust-lightning/", rev = "77fc8a11b0f10fb7e31f246b59a37455d4f0d41d" }
bdk-ldk = { git = "https://github.com/get10101/bdk-ldk", rev = "9b5d237e9305e1ed1f39619bd7ed8056ff7cc6e7" } # unreleased (we might want to consider moving that lib to the crates subfolder directly!)
