[package]
name = "ln-dlc-node"
version = "0.1.0"
edition = "2021"
description = "A common interface for using Lightning and DLC channels side-by-side."

[dependencies]
bitcoin = "0.29"
bitcoin-bech32 = "0.12"
dlc-manager = { version = "0.3.0", features = ["use-serde"] }
dlc-messages = { version = "0.3.0" }
dlc-sled-storage-provider = { version = "0.1.0" }
electrs-blockchain-provider = { version = "0.1.0" }
hex = "0.3"
lightning = { version = "0.0.113", features = ["max_level_trace"] }
lightning-background-processor = { version = "0.0.113" }
lightning-block-sync = { version = "0.0.113", features = ["rpc-client"] }
lightning-invoice = { version = "0.20" }
lightning-net-tokio = { version = "0.0.113" }
lightning-persister = { version = "0.0.113" }
lightning-rapid-gossip-sync = { version = "0.0.113" }
p2pd-oracle-client = { version = "0.1.0" }
rand = "0.4"
simple-wallet = { version = "0.1.0" }
tokio = { version = "1", features = ["io-util", "macros", "rt", "rt-multi-thread", "sync", "net", "time"] }
tracing = "0.1.37"
